/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cg;

import org.junit.Test;

import com.cg.FindMaximum;

import static org.junit.Assert.*;

public class FindMaximumTest {

	@Test
	public void testMaximumTestMethod1() {
		FindMaximum obj = new FindMaximum();
		assertEquals((Integer) 15, obj.maximumTest(15, 10, 5));
	}

	@Test
	public void testMaximumTestMethod2() {
		FindMaximum obj = new FindMaximum();
		assertEquals((Integer) 15, obj.maximumTest(5, 15, 10));
	}

	@Test
	public void testMaximumTestMethod3() {
		FindMaximum obj = new FindMaximum();
		assertEquals((Integer) 15, obj.maximumTest(10, 5, 15));
	}
}
